# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Chang Target
        working-directory: ${{runner.workspace}}
        run: |
          git remote remove origin
          git remote set-url origin https://gitee.com/dorbmon/judo-language
          git config --global user.email "1263592223@qq.com"
          git config --global user.name "Dorbmon"
          git add .
          git commit -m "Update from https://github.com/Ruixues/Judo"
          git push https://${{ secrets.GITEE }}:${{ secrets.GITEEPASSWORD }}@gitee.com/dorbmon/judo-language.git --all
